# Generated by Django 3.2.3 on 2021-05-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('short_url', models.URLField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
