# Generated by Django 3.2.3 on 2021-05-23 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0002_auto_20210523_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 12, 32, 57, 983031), editable=False),
        ),
    ]
