# Generated by Django 3.2.3 on 2021-05-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0003_alter_url_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
