# Generated by Django 3.2.3 on 2021-05-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0013_auto_20210523_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 13, 49, 23, 219078), editable=False),
        ),
    ]
