# Generated by Django 3.2.3 on 2021-05-23 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_short', '0014_alter_url_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 23, 13, 54, 12, 345041), editable=False),
        ),
    ]
